apiVersion: v1
kind: Service
metadata:
  name: notification-api-test-svc
  namespace: notification-api-test
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30015
    protocol: TCP
  selector:
    app: notification-api-test