kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mongodb-standalone-test
  namespace: notification-api-test
spec:
  storageClassName: ""
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi