apiVersion: v1
kind: Service
metadata:
  name: database-test
  namespace: notification-api-test
  labels:
    app: database-test
spec:
  type: NodePort
  ports: 
  - port: 27017
    targetPort: 27017
    nodePort: 30016
    protocol: TCP
  selector:
    app: database-test