apiVersion: v1
kind: PersistentVolume
metadata:
    name: mongodb-standalone-test
    namespace: notification-api-test
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /k8-notification-test
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
            - karbon-hukbctldev-421f6c-k8s-worker-0