apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: notification-api-application
  namespace: argocd
spec:
  project: notification-api

  source:
    repoURL: https://humanoseguros@dev.azure.com/humanoseguros/NotificationAPI/_git/notification-api-ops
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: notification-api

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true